### ISSUE TITLE
File not found - '*.pyc'

### ISSUE THREAD

**Issue by Undeadlol1** [glutanimate/cloze-overlapper#27]
When i am trying to build project locally there is an error:
```
Getting Git version info...

=== Build task 1/1 ===

--- Building Cloze Overlapper v0.4.0-alpha.0 for anki21/local ---

Cleaning repository...
File not found - '*.pyc'
Error while running command: 'find "."  \( -name '*.pyc' -o -name '*.pyo' -o -name '__pycache__' \) -delete'
```

![image](https://user-images.githubusercontent.com/4124323/59150382-fdf66e00-8a3b-11e9-9cdb-044443cd55bd.png)

Using PowerShell on Windows 10.

**Comment by Undeadlol1** [comment]
Update: works fine in MacOS.

![image](https://user-images.githubusercontent.com/4124323/59150435-dfdd3d80-8a3c-11e9-9cf2-9fc6f7ed18a1.png)

**Comment by Undeadlol1** [comment]
Update 2:
Anki doesn't load properly.
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Cloze Overlapper':
Traceback (most recent call last):
  File "aqt/addons.py", line 80, in loadAddons
  File "/Users/undeadlol1/Library/Application Support/Anki2/addons21/cloze_overlapper/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/Users/undeadlol1/Library/Application Support/Anki2/addons21/cloze_overlapper/main.py", line 42, in <module>
    from .gui.options_global import initializeOptions
  File "/Users/undeadlol1/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/options_global.py", line 49, in <module>
    from .forms import settings_global
  File "/Users/undeadlol1/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/forms/__init__.py", line 41, in <module>
    from .anki21 import *  # noqa: F401
ModuleNotFoundError: No module named 'cloze_overlapper.gui.forms.anki21'
```
