### ISSUE TITLE
Add-on impossible to be installed on Anki

### ISSUE THREAD

**Issue by gbeyrend** [Glutanimate/cloze-overlapper#50]
#### Problem description

I downloaded the Add on Cloze Overlapper and followed precisely your YouTube on how to install it in Anki. 
However here I receive the follwoing error message when I restart Anki:

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨cloze_overlapper⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/main.py", line 42, in <module>
    from .gui.options_global import initializeOptions
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/options_global.py", line 49, in <module>
    from .forms import settings_global
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/forms/__init__.py", line 41, in <module>
    from .anki21 import *  # noqa: F401
ModuleNotFoundError: No module named 'cloze_overlapper.gui.forms.anki21'

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version: 2.1.33

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-09-03 13:15:50
Add-ons possibly involved: ⁨cloze_overlapper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/main.py", line 42, in <module>
    from .gui.options_global import initializeOptions
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/options_global.py", line 49, in <module>
    from .forms import settings_global
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/forms/__init__.py", line 41, in <module>
    from .anki21 import *  # noqa: F401
ModuleNotFoundError: No module named 'cloze_overlapper.gui.forms.anki21'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt/main.py", line 1094, in onPrefs
  File "aqt/__init__.py", line 105, in open
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-8>", line 2, in __init__
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 629, in repl
  File "aqt/preferences.py", line 24, in __init__
AttributeError: 'NoneType' object has no attribute 'backend'

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Catalina 
- version: 10.15.6

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/38186063/92219489-e99d5d00-ee9a-11ea-9006-8175f6358cd6.png)

Add ons installed:
Advanced Browser
Anki Connect
Batch Editing
Button Colours Good Agzain
Cloze_overlapper
Free Weekend
French Keyboard
Hierarchical Tags 2
Image occlusion Enhanced
Load balancer
Open Added Today from Reviewer
Pop Up dictionnary beta
Progres Graph
Review Heatmap
Search and Replace Tag

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

When loading '⁨cloze_overlapper⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/main.py", line 42, in <module>
    from .gui.options_global import initializeOptions
  File "/Users/gbeyrend/Library/Application Support
[ANki.docx](https://github.com/glutanimate/cloze-overlapper/files/5173631/ANki.docx)
/Anki2/addons21/cloze_overlapper/gui/options_global.py", line 49, in <module>
    from .forms import settings_global
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/forms/__init__.py", line 41, in <module>
    from .anki21 import *  # noqa: F401
ModuleNotFoundError: No module named 'cloze_overlapper.gui.forms.anki21'


```

**Comment by glutanimate** [comment]
Hi there,

Which YouTube tutorial do you mean exactly? The only official documentation for building the add-on from source code is this: https://github.com/glutanimate/cloze-overlapper#building

**Comment by gbeyrend** [comment]
Oh sorry I will check it out now!! 
Thanks for your quick reply! I gave you 5$ and an upvote for you btw :) Thanks for your work

**Comment by gbeyrend** [comment]
I did this method but it does not work so I will keep the issue opened.

**Comment by gbeyrend** [comment]
I didn't download the correct version. Sorry for my mistake. I should have downloaded 2.1
This issue can be solved 👍🏼
