### ISSUE TITLE
Impossible to use the Add on in Anki

### ISSUE THREAD

**Issue by gbeyrend** [Glutanimate/cloze-overlapper#51]
#### Problem description

Installation of the adds-on is going well. The Adds-on is correctly installed. 
Once I want to create a card, I got an error if I click on "Generate overlapping clozes" or if I click on overlapping cloze options. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:* 2.1.33

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.15.6
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-09-03 13:15:50
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2020-04-23T00:45, 'None', '']
    AnkiConnect ['2055492159', 2020-07-12T21:54, 'None', '']
    Batch Editing ['291119185', 2019-06-02T20:47, 'None', '']
    Button Colours Good Again ['2494384865', 2020-02-09T13:18, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T13:37, 'None', '']
    Free Weekend - or Any Other Day ['742185195', 2020-04-10T13:57, 'None', '']
    French Keyboard Support AZERTY ['228944836', 2019-03-28T13:36, 'None', '']
    Hierarchical Tags 2 ['594329229', 2020-04-11T18:36, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    Open Added Today from Reviewer ['861864770', 2019-02-22T20:19, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T18:32, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T08:26, 'None', '']
    ReviewHeatmap ['723520343', 2019-08-03T17:14, 'None', '']
    Search and Replace Tags ['138501288', 2017-08-29T20:58, 'None', '']
    load balancer ['1417170896', 2020-08-06T01:58, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155 138501288 1417170896 153625306 2055492159 228944836 2494384865 266436365 291119185 594329229 723520343 742185195 861864770 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Catalina
- version: 10.15.6

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/38186063/92227658-df815b80-eea6-11ea-974c-b21c5ee17f88.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-03 13:15:50
Add-ons possibly involved: ⁨Cloze Overlapper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 493, in handler
  File "aqt/editor.py", line 481, in <lambda>
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 154, in <lambda>
    editor.saveNow(lambda: callback(editor, *args, **kwargs))
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 283, in onOlClozeButton
    return onFieldReady()
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 270, in onFieldReady
    overlapper.add()
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "/Users/gbeyrend/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 203, in updateNote
    note.flush()
  File "anki/notes.py", line 67, in flush
AssertionError

```

**Comment by gbeyrend** [comment]
Anki just needs to be down graded to version 26 as suggested by the author.
