### ISSUE TITLE
Unable to add cards: Assertion Error

### ISSUE THREAD

**Issue by k-liang** [Glutanimate/cloze-overlapper#54]
Hello,

In the Anki version 2.1.33 my cloze-overlapper stops working with the following error message:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-15 21:13:03
Add-ons possibly involved: ⁨cloze_overlapper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 493, in handler
  File "aqt/editor.py", line 481, in <lambda>
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-18>", line 2, in _addCards
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/kaifengliang/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 301, in onAddCards
    ret, total = overlapper.add()
  File "/Users/kaifengliang/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "/Users/kaifengliang/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 203, in updateNote
    note.flush()
  File "anki/notes.py", line 67, in flush
AssertionError
```

With the guidance on another thread I have tried to install the last stable version of Anki 2.1.26, but with no luck as the add-on now displays “no configuration is found” and is disabled.

I would really appreciate your help!

Thank you,

**Comment by PlEaSeH** [comment]
https://github.com/glutanimate/cloze-overlapper/issues/42
