### ISSUE TITLE
Error message while adding cards in Anki 2.1.33

### ISSUE THREAD

**Issue by FuriousNutSlaps** [Glutanimate/cloze-overlapper#55]
***IMPORTANT*** 

The easiest fix that I found online was to downgrade to 2.1.26 which actually worked for me so yay! But one person in Glutaminate's Patreon & another on this thread commented that his error still persisted after downgrading to 2.1.26. 

Thank you!  

#### Problem description

Error message pops up when trying to add a cloze overlapper card in Anki 2.1.33. The error also pops up if -

1. I go to Tools > Cloze Overlapper Options > Clicking on Ok. 

2. While in the process of adding a card, before actually adding it, clicking on the settings icon to open the cloze overlapper settings window, and clicking Ok.

#### Checklist

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

2.1.33

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-09-18 18:14:54
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    BetterTags ['bettertags', 2020-01-29T02:00, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T18:07, 'None', '']
    Field History ['1247884413', 2020-02-25T09:38, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T09:42, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T07:51, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-10-19T19:36, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-02-05T12:46, 'None', '']
    Review Heatmap ['review_heatmap', 2018-10-29T03:36, 'None', '']
    TagSelectorV2 ['1022577188', 2020-08-13T08:39, 'None', mod]
    Visual Feedback for Reviews ['review_feedback', 2020-01-30T01:13, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1022577188 1247884413 1374772155 153625306 516643804
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    ReMemorize Rescheduler with sibling and logging v140 ['323586997', 2020-04-17T12:37, 'None', mod]

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Windows 10
- version: 1903 (OS Build 18362.1082)

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/71527183/93642798-53317580-fa1c-11ea-8fa6-7c4ef8ddf4f1.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-18 18:14:54

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\editor.py", line 481, in <lambda>
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-32>", line 2, in _addCards
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\Hp\AppData\Roaming\Anki2\addons21\cloze_overlapper\editor.py", line 301, in onAddCards
    ret, total = overlapper.add()
  File "C:\Users\Hp\AppData\Roaming\Anki2\addons21\cloze_overlapper\overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "C:\Users\Hp\AppData\Roaming\Anki2\addons21\cloze_overlapper\overlapper.py", line 203, in updateNote
    note.flush()
  File "anki\notes.py", line 67, in flush
AssertionError

```

**Comment by PlEaSeH** [comment]
https://github.com/glutanimate/cloze-overlapper/issues/42

**Comment by Farinata** [comment]
When we can expect the addon new version release?

**Comment by SF1000X** [comment]
Downgraded to older versions of Anki and they got stuck syncing. Upgraded back to 2.1.35. Wish there was an update for the Overlapper I REALLY need this Feature.

Are there any other alternative routes. I need my Cloze card to function like this...

{{c1::}} Revealed {{c2::}} Hidden {{c3::}} Hidden ::enter:: {{c1::}} Revealed {{c2::}} Revealed {{c3::}} Hidden ::enter:: {{c1::}} Revealed {{c2::}} Revealed {{c3::}} Revealed

**Comment by SF1000X** [comment]
@FuriousNutSlaps I tried downloading to 2.1.26 and it freezes while its synching.

any suggestions?

**Comment by miezmiuremiezutschi** [comment]
@SF1000X This could be an option: https://ankiweb.net/shared/info/2084557901, alternatively this is a fix : https://www.reddit.com/r/Anki/comments/jlj1yy/fixing_cloze_overlapper_for_2128/

**Comment by boydkelly** [comment]
> @SF1000X This could be an option: https://ankiweb.net/shared/info/2084557901, alternatively this is a fix : https://www.reddit.com/r/Anki/comments/jlj1yy/fixing_cloze_overlapper_for_2128/

I tried the fix and it <sort> of works but I'm still having various issues which is not inspiring confidence.   I haven't used in a long time, but would be really great to see the plugin itself fixed and updated.

**Comment by michalrus** [comment]
While waiting for an official release, you can try a pure JavaScript template which is simpler, and works on mobile, too – https://github.com/michalrus/anki-simple-cloze-overlapper

**Comment by boydkelly** [comment]
> While waiting for an official release, you can try a pure JavaScript template which is simpler, and works on mobile, too – https://gist.github.com/michalrus/fe16637f6bdc329ba35f635a4b4994bc

Awesome!   Just trying this out.   Seems to work great!
