### ISSUE TITLE
Error when changing Original Field.

### ISSUE THREAD

**Issue by thecakeisal1e** [Glutanimate/cloze-overlapper#57]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-12 21:23:55

Caught exception:
Traceback (most recent call last):
  File "%appdata%\Anki2\addons21\cloze_overlapper\gui\options_global.py", line 95, in onAccept
    reset_req = self.renameFields()
  File "%appdata%\Anki2\addons21\cloze_overlapper\gui\options_global.py", line 130, in renameFields
    idx = mw.col.models.fieldNames(model).index(oldname)
ValueError: 'Expression' is not in list

Trying to change the field from "Expression" to anything else.

**Comment by phillipjohnston** [comment]
I get a similar problem when trying to add a card now.

```
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-16 18:50:04
Add-ons possibly involved: ⁨Cloze Overlapper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 493, in handler
  File "aqt/editor.py", line 483, in <lambda>
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-6>", line 2, in _addCards
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/phillip/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 301, in onAddCards
    ret, total = overlapper.add()
  File "/Users/phillip/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "/Users/phillip/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 203, in updateNote
    note.flush()
  File "anki/notes.py", line 67, in flush
AssertionError
```

**Comment by phillipjohnston** [comment]
Ah, I guess mine is #55.
