### ISSUE TITLE
cloze overlapper cards are not being reviewed in the right order

### ISSUE THREAD

**Issue by abdsara** [Glutanimate/cloze-overlapper#59]
#### Problem description

I have created several cards with the cloze overlapper. When it comes to reviewing I noticed that they are in a weird order, which makes it impossible to efficiently review them. I clicked both on Override sibling-spacing for new overlapping clozes as well as for overlapping cloze review. 

However when I click on okay it appears that it won't work. When I close the app and open it while clicking on shift, all of the cloze overlapper buttons disappear so get removed. I also downgraded to Anki 2.1.26 beforehand , to avoid any issues with the latest anki version.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-10 21:32:21

Caught exception:
Traceback (most recent call last):
  File "C:\Users\saraa\AppData\Roaming\Anki2\addons21\cloze_overlapper\gui\options_global.py", line 107, in onAccept
    config.save(reset=reset_req)
  File "C:\Users\saraa\AppData\Roaming\Anki2\addons21\cloze_overlapper\libaddon\anki\configmanager.py", line 219, in save
    saver(self._config[name])
  File "C:\Users\saraa\AppData\Roaming\Anki2\addons21\cloze_overlapper\libaddon\anki\configmanager.py", line 460, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "lib\site-packages\anki\config.py", line 60, in __setitem__
  File "lib\site-packages\anki\config.py", line 36, in set
  File "lib\site-packages\anki\rsbackend.py", line 591, in set_config_json
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

```python

```

**Comment by abdsara** [comment]
Also the "Debug Info":     
    Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-12-10 21:32:21
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Anki Simulator ['anki_simulator', 2020-03-28T20:47, 'None', '']
    Automatic Basic to Cloze ['2105427255', 2020-05-09T10:57, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T13:37, 'None', '']
    External Note Editor for the Browser ['browser_external_note_editor', 2020-03-10T18:42, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T19:45, 'None', '']
    PDF Glossary Exporter ['pdf_glossary', 2019-08-19T14:35, 'None', '']
    Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-03-31T22:13, 'None', '']
    Spell Checker ['spell_checker', 0, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    2105427255 295889520
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
