### ISSUE TITLE
ModuleNotFoundError: No module named 'cloze_overlapper.gui.forms.anki21

### ISSUE THREAD

**Issue by rasulkireev** [Glutanimate/cloze-overlapper#61]
#### Problem description

Here is what I did:

1. I have pulled the latest commit  of the main branch (`git clone ...`)
2. I have `built` the addon with `aab build`
3. In Anki I went to addon page and dragged the `cloze-overlapper-v0.4.0-alpha.0-anki21.ankiaddon` file to the addon list. 
4. I then restarted the app and got the `ModuleNotFoundError` error.

Could you please help me resolving this issue?

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1
``` 
    Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.15.7
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-12-14 12:01:12
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Cloze Anything ['330680661', 2019-12-30T01:17, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T15:37, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T05:21, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155 330680661
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
```

#### Error message
```python
When loading '⁨Cloze Overlapper⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/u1082926/Library/Application Support/Anki2/addons21/cloze_overlapper/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/Users/u1082926/Library/Application Support/Anki2/addons21/cloze_overlapper/main.py", line 42, in <module>
    from .gui.options_global import initializeOptions
  File "/Users/u1082926/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/options_global.py", line 49, in <module>
    from .forms import settings_global
  File "/Users/u1082926/Library/Application Support/Anki2/addons21/cloze_overlapper/gui/forms/__init__.py", line 41, in <module>
    from .anki21 import *  # noqa: F401
ModuleNotFoundError: No module named 'cloze_overlapper.gui.forms.anki21'
```

**Comment by infinyte7** [comment]
First install  
```
pip install pyqt5-tools
```
Then
```
git clone https://github.com/glutanimate/cloze-overlapper.git
cd cloze-overlapper
aab build
```
