### ISSUE TITLE
Unable to create cloze overlapping

### ISSUE THREAD

**Issue by idkei** [Glutanimate/cloze-overlapper#64]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Hi, I've again started using cloze overlapper again and I've just upgraded from Anki version 2.1.26 to 2.1.35 and this is what I got as error. 

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2
Platform: Mac 10.12.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-12 06:29:28
Add-ons possibly involved: ⁨Cloze Overlapper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 493, in handler
  File "aqt/editor.py", line 483, in <lambda>
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-146>", line 2, in _addCards
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/nebula/Library/Application Support/Anki2/addons21/cloze_overlapper/editor.py", line 301, in onAddCards
    ret, total = overlapper.add()
  File "/Users/nebula/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 117, in add
    self.updateNote(fields, full, setopts, custom)
  File "/Users/nebula/Library/Application Support/Anki2/addons21/cloze_overlapper/overlapper.py", line 203, in updateNote
    note.flush()
  File "anki/notes.py", line 67, in flush
AssertionError

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Mac OS 10.12
- version: 2.1.35

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by idkei** [comment]
Resolved with this link
https://www.reddit.com/r/Anki/comments/jlj1yy/fixing_cloze_overlapper_for_2128/

Thanks!

**Comment by glutanimate** [comment]
Hey idkei,

Thanks for the detailed report!

My apologies about the issues with the add-on at the moment. I'm currently working on an updated version that will be coming out later this month and adding support for all recent Anki releases.

Until then, the fix you link is a great way to bridge the gap.
