### ISSUE TITLE
Error while starting anki with compiled addon

### ISSUE THREAD

**Issue by DyeffersonAz** [Glutanimate/cloze-overlapper#65]
#### Problem description

I compiled it with no errors using `aab`, but when I install it Anki returns with an error.

#### Checklist
 - [x] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb _(I compiled it as Ankiweb version is unfortunately outdated.)_
 - [X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Anki ⁨2.1.38 (355e4cd5)⁩

##### Anki 2.1 debug info

```
    Anki 2.1.38 (355e4cd5) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-03-19 14:52:37
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AddonBackup ['162231225', 2019-01-16T05:53, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T10:37, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T01:12, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2021-01-04T13:32, 'None', '']
    More Overview Stats 21 ['738807903', 2021-02-05T14:35, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2021-01-04T13:31, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T11:14, '20.12.13i151', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T10:23, 'None', '']
```
*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Ubuntu
- version: 20

![image](https://user-images.githubusercontent.com/16638560/111852799-212f9c00-88f7-11eb-82d7-d385f85f3424.png)

#### Error message

```python
Traceback (most recent call last):
  File "aqt/addons.py", line 210, in loadAddons
  File "/home/dyefferson/.local/share/Anki2/addons21/cloze_overlapper/__init__.py", line 41, in <module>
    from . import main  # noqa: F401
  File "/home/dyefferson/.local/share/Anki2/addons21/cloze_overlapper/main.py", line 42, in <module>
    from .gui.options_global import initializeOptions
  File "/home/dyefferson/.local/share/Anki2/addons21/cloze_overlapper/gui/options_global.py", line 49, in <module>
    from .forms import settings_global
  File "/home/dyefferson/.local/share/Anki2/addons21/cloze_overlapper/gui/forms/__init__.py", line 41, in <module>
    from .anki21 import *  # noqa: F401
ModuleNotFoundError: No module named 'cloze_overlapper.gui.forms.anki21'
```

**Comment by langfield** [comment]
Make sure you've got `pyqt5-tools` installed.
